/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_org_opensearch_knn_reorder_FaissKMeansService
#define _Included_org_opensearch_knn_reorder_FaissKMeansService
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jintArray JNICALL Java_org_opensearch_knn_reorder_FaissKMeansService_kmeans
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

JNIEXPORT jobject JNICALL Java_org_opensearch_knn_reorder_FaissKMeansService_kmeansWithDistances
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

JNIEXPORT jlong JNICALL Java_org_opensearch_knn_reorder_FaissKMeansService_storeVectors
  (JNIEnv *, jclass, jobjectArray);

JNIEXPORT void JNICALL Java_org_opensearch_knn_reorder_FaissKMeansService_freeVectors
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
