/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_reorder_FaissIndexService */

#ifndef _Included_org_opensearch_knn_reorder_FaissIndexService
#define _Included_org_opensearch_knn_reorder_FaissIndexService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_reorder_FaissIndexService
 * Method:    buildAndWriteIndex
 * Signature: (JII[ILjava/lang/String;Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_reorder_FaissIndexService_buildAndWriteIndex
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jstring, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
